version: "3.9"

services:
  consul:
    image: consul:1.1.0
    hostname: localhost
    ports:
      - 8500:8500
  postgres:
    container_name: auth_db
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data:
    name: auth_db_data
