package com.example.authservice.model.enums;

public enum RoleType {
    ROLE_SYSTEM_ADMIN,
    ROLE_SYSTEM_MODERATOR,
    ROLE_BUREAUCRACY_USER,
    ROLE_MEDICAL_USER,
    ROLE_BUREAUCRACY_ADMIN,
    ROLE_MEDICAL_ADMIN,
    ROLE_BUREAUCRACY_MANIPULATOR,
    ROLE_MEDICAL_MANIPULATOR
}
