CREATE TABLE AUTH_USER(
    ID BIGINT PRIMARY KEY,
    USERNAME VARCHAR UNIQUE NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    EMAIL VARCHAR
);

CREATE TABLE AUTH_ROLE(
    ID INT PRIMARY KEY,
    ROLE_NAME VARCHAR
);

CREATE TABLE USER_ROLE(
    USER_ID BIGINT REFERENCES AUTH_USER(ID),
    ROLE_ID INT REFERENCES AUTH_ROLE(ID)
);


CREATE SEQUENCE user_seq increment 1 start 1;